name: Trigger Jenkins Workflow
on:
  workflow_call:

jobs:
  trigger:
    name: Trigger jenkins workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        uses: appleboy/jenkins-action@master
        with:
          url: "https://fe30-58-186-75-40.ngrok-free.app"
          user: "20424071"
          token: "11bab49eb402a350e6f2402b0011515b08"
          job: "ACN-Project-3-Workflow-Demo"
